services:
  gin-app:
    image: golang:1.24
    ports:
      - "8888:8888"
    volumes:
      - ./file:/app
    working_dir: /app
    command:
        - sh
        - -c
        - |
          go build -o portfolio main.go && ./portfolio
